syntax = "proto3";

package voter.tokenfactory.v1;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "voter/tokenfactory/v1/params.proto";

option go_package = "voter/x/tokenfactory/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // CreateDenom defines the CreateDenom RPC.
  rpc CreateDenom(MsgCreateDenom) returns (MsgCreateDenomResponse);

  // UpdateDenom defines the UpdateDenom RPC.
  rpc UpdateDenom(MsgUpdateDenom) returns (MsgUpdateDenomResponse);

  // DeleteDenom defines the DeleteDenom RPC.
  rpc DeleteDenom(MsgDeleteDenom) returns (MsgDeleteDenomResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "voter/x/tokenfactory/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless overwritten).
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  // params defines the module parameters to update.

  // NOTE: All parameters must be supplied.
  Params params = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgCreateDenom defines the MsgCreateDenom message.
message MsgCreateDenom {
  option (cosmos.msg.v1.signer) = "owner";
  string owner = 1;
  string denom = 2;
  string description = 3;
  string ticker = 4;
  int64 precision = 5;
  string url = 6;
  int64 max_supply = 7;
  int64 supply = 8;
  bool can_change_max_supply = 9;
}

// MsgCreateDenomResponse defines the MsgCreateDenomResponse message.
message MsgCreateDenomResponse {}

// MsgUpdateDenom defines the MsgUpdateDenom message.
message MsgUpdateDenom {
  option (cosmos.msg.v1.signer) = "owner";
  string owner = 1;
  string denom = 2;
  string description = 3;
  string ticker = 4;
  int64 precision = 5;
  string url = 6;
  int64 max_supply = 7;
  int64 supply = 8;
  bool can_change_max_supply = 9;
}

// MsgUpdateDenomResponse defines the MsgUpdateDenomResponse message.
message MsgUpdateDenomResponse {}

// MsgDeleteDenom defines the MsgDeleteDenom message.
message MsgDeleteDenom {
  option (cosmos.msg.v1.signer) = "owner";
  string owner = 1;
  string denom = 2;
}

// MsgDeleteDenomResponse defines the MsgDeleteDenomResponse message.
message MsgDeleteDenomResponse {}
